In [1]:
import numpy as np

In [5]:
np.zeros((0,10))

array([], shape=(0, 10), dtype=float64)

In [6]:
# Create an array of 10 zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Create an array of 10 ones

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
# Create an array of 10 fives

np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [44]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [14]:
# Create an array of the integers from 10 to 50

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [18]:
# Create an array of all the even integers from 10 to 50

np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [26]:
# Create a 3:3 matrix with values ranging from 0 to 8

np.arr([0,1,2],[3,4,5],[6,7,8])

AttributeError: module 'numpy' has no attribute 'arr'

In [46]:
# Create a 3:3 matrix with values ranging from 0 to 8

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
# Create a 3:3 matrix with values ranging from 0 to 8

a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
# Create a 3:3 matrix with values ranging from 0 to 8

matrix = [[0,1,2],[3,4,5],[6,7,8]]

In [28]:
np.array(matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
# Create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# Use numpy to generate a random number between 0 and 1
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [50]:
# Use numpy to generate a random number between 0 and 1
np.random.rand(1)

array([0.95627635])

In [51]:
# Wrong - Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(5,5)

array([[ 1.00658787,  1.07291217, -0.14424063,  2.35495151,  0.61836201],
       [-0.77015298, -0.4070495 ,  0.20579964, -0.36673993,  0.62071099],
       [ 0.14159576, -0.20925694, -0.03608808,  0.60494046, -0.88602578],
       [ 0.72417534,  0.56839281,  0.64090837, -1.0607691 , -1.02837611],
       [-0.80918223, -0.77191155,  0.4981809 ,  1.75489655,  0.83846194]])

In [37]:
# Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 1.088148  ,  1.1976982 ,  1.22081518, -2.1776823 , -0.36817322,
        1.02228424,  0.34077439,  0.24171335,  1.11407796, -1.19605152,
       -0.66832652,  1.62320136, -0.62111194, -0.19005982, -0.21951392,
        0.60302848, -0.07178158, -0.29370558, -0.25934555, -1.92559701,
       -1.03429314,  0.16757787,  3.2784903 ,  0.94249044, -0.25831995])

In [52]:
# Create the matrix
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [53]:
# Create the matrix
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [55]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [56]:
# Create an array of 20 linearly spaced points between 0 and 1

np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy indexing and selection

In [41]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [58]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [64]:
mat[3:4,4:]

array([[20]])

In [65]:
mat[3,4]

20

In [69]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [70]:
mat[:3,1]

array([ 2,  7, 12])

In [77]:
mat[4:,]

array([[21, 22, 23, 24, 25]])

In [79]:
mat[-1:,]

array([[21, 22, 23, 24, 25]])

In [80]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
# Get the sum of all values in mat

mat.sum()

325

In [84]:
np.sum(mat)

325

In [85]:
np.std(mat)

7.211102550927978

In [86]:
mat.std()

7.211102550927978

In [91]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [92]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])