In [1]:
my_list = [1,2,3]

In [45]:
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
# casting a list in array, 1-D array
arr = np.array(my_list)

In [4]:
# array after casting, 1-D array
arr

array([1, 2, 3])

In [6]:
# list of list

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
# casting lists in array, 2-D array

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# numpy array by arange

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# numpy array by arange

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# 1-D vector

np.zeros(3)

array([0., 0., 0.])

In [13]:
# for number of zeros in rows and columns

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
# linspace returns evenly spaced numbers over a specified interval, 3rd argument for number of points you want
# 1-D array

# 10 evenly spaced points from 0-5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [48]:
# 1-D array

# 100 evenly spaced points from 0-5
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [49]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
# This is going to create an array of the shape you pass in and it's going to populate it with random samples from a
# uniform distribution over 0 to 1.

# That means if i want just a one-dimensional array of random numbers uniformly distributed from 0-1
# I can pass in a single digit and I'll get back that 1-D array.

np.random.rand(5)

array([0.21307921, 0.91044065, 0.58991248, 0.30430838, 0.56620067])

In [26]:
np.random.randn(2)

array([ 0.16031074, -1.32927356])

In [27]:
# not from a distribution 0-1 but instead from a standard normal distribution center around zero

np.random.randn(4,4)

array([[-0.05965186, -0.1827853 , -0.66227121,  0.0050931 ],
       [ 0.52348816, -1.09632178,  1.46245458,  0.49598944],
       [ 0.02223838,  0.63054987,  1.07542424,  0.49757779],
       [-0.99759349, -0.44563097, -0.23766983, -1.20420136]])

In [28]:
# low to high numbers
# low, high and then the actual size you want

np.random.randint(1,100)

59

In [50]:
# 10 random integers from 1-100, inclusive on the low end and exclusive on the high end

np.random.randint(1,100,10)

array([40, 27, 41, 60, 68, 49, 80, 87, 92, 60])

In [51]:
# 1-D array from 0-24

arr = np.arange(25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
# 10 random integers from 0-50

ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([ 8, 11, 41, 33, 34,  1, 47, 10,  4, 29])

In [54]:
# 25 digits in array, 5*5 = 25
# number of rows * number of columns

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.max()

47

In [37]:
ranarr.min()

1

In [38]:
ranarr

array([ 8, 11, 41, 33, 34,  1, 47, 10,  4, 29])

In [39]:
ranarr.argmax()

6

In [40]:
ranarr.argmin()

5

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

# Indexing and slicing of array

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
# broadcasting value equal to 100
# 0-4, 1st five elements are 100 value

arr[0:5] = 100

In [64]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
slice_of_arr = arr[0:6]

In [74]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [76]:
# broadcasting

slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [77]:
slice_of_arr[:] = 99

In [78]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [92]:
# If you actually grab a slice of array and set it as a variable without explicitly saying that you want to
# copy of the array, you are just viewing a link to the original array and that changes you do will actually
# affect that original array.

arr_copy = arr.copy()

In [93]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [94]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [95]:
arr_copy[:] = 100

In [96]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [97]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2-D array

In [100]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [101]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [103]:
# 1st row and 1st column

arr_2d[0][0]

5

In [105]:
# entire row of index 0

arr_2d[0]

array([ 5, 10, 15])

In [108]:
# index 1 of the row 1
# from the row 1, index 1

arr_2d[1][1]

25

In [110]:
# from the row 2, index 1

arr_2d[2][1]

40

In [111]:
arr_2d[2,1]

40

In [112]:
arr_2d[1,2]

30

In [113]:
arr_2d[1][2]

30

In [139]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [141]:
# grab everything upto column 2 and then grab from column 2 onwards
# grab everything but not including rows 0 and 1 as the colon
# but then don't include two, we are saying slice it too

# grab everything from column 1 all the way to end
# drop column 0

# :2 - rows
# 1: - columns

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [117]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

# Conditional selection

In [121]:
arr = np.arange(1,11)

In [122]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [124]:
bool_arr = arr > 5

In [125]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [126]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [127]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [128]:
arr[arr<3]

array([1, 2])

# Exercise

In [130]:
arr_2d = np.arange(50).reshape(5,10)

In [131]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [137]:
# grab 13,14
# grab 23,24

# 1:3 rows
# 3:5 columns

arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [134]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Numpy operations

# Array with array
# Array with scalars
# Universal array functions

In [142]:
arr = np.arange(0,11)

In [143]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [145]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [146]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [147]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [148]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [149]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [150]:
arr / arr

C:\Users\Muhammad Iqbal\AppData\Local\Temp\ipykernel_21916\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [151]:
1 / arr

C:\Users\Muhammad Iqbal\AppData\Local\Temp\ipykernel_21916\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [152]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [153]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [154]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [155]:
np.max(arr)

10

In [156]:
np.min(arr)

0

In [157]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [158]:
np.log(arr)

C:\Users\Muhammad Iqbal\AppData\Local\Temp\ipykernel_21916\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])